name: nothin_but_the_bloc
description: A library that aims to make BLoC principles more intuitive to implement.
version: 0.0.2
homepage: https://github.com/andrewackerman/nbnt
repository: https://github.com/andrewackerman/nbnt
issue_tracker: https://github.com/andrewackerman/nbnt/issues
author: Andrew Ackerman <andrew.ackie@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.0.0
  rxdart: ^0.22.0

dev_dependencies:
  test: ^1.0.0
